-- Users table seeds here (Example)
DELETE FROM resources;

INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (1, 'https://cooking.nytimes.com/guides/1-how-to-make-pizza', 'How to Make Pizza', 'You can make pizza at home. In fact, you can make pizza that will equal some of the best on the planet. With planning and practice, you can become good at it — even if you are a relatively novice cook. We are here to help that happen.', 'https://www.simplyrecipes.com/thmb/pjYMLcsKHkr8D8tYixmaFNxppPw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__09__easy-pepperoni-pizza-lead-3-8f256746d649404baa36a44d271329bc.jpg');
INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (2, 'https://www.womenshealthmag.com/fitness/a19918535/how-to-do-a-handstand/', 'How to Do a Handstand', 'Youre probably used to seeing handstands and handstand variations (think: handstand shoulder taps #casual) in your TikTok feed by now. Learning how to do a handstand is not only an impressive party trick—it will score you heaps of mental and physical bennies, too.', 'https://media1.popsugar-assets.com/files/thumbor/znO3qdonCzjNu7BQNVdLBNlzTn0/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2016/10/31/649/n/1922729/84005cd0581756accefb01.88164494_edit_img_image_7676437_1453065000/i/Learn-How-Do-Handstand.jpg');
INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (3, 'https://www.longfield-gardens.com/article/how-to-water-your-plants', 'How to Water Plants', 'Anyone can pour water on a plant. But it takes time and experience to understand how plants use water and the many variables that come into play. These include the type of plant, its size, the soil texture, recent weather, sun exposure, time of day and time of year. In short, watering your garden shouldn''t be a rote task. The amount of water a plant requires is constantly changing, so you need to be paying attention.', 'https://cdn11.bigcommerce.com/s-1b9100svju/product_images/uploaded_images/ad-options-articles-84-.jpg');
INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (4, 'https://blog.nationwide.com/home/home-maintenance/how-to-clean-house-fast/', 'Top 11 Cleaning Tips', 'Everyone hates to clean but everyone loves a clean house. Is there a best way to clean your house fast?.', 'https://www.thespruce.com/thmb/d5GHeqqBWGoNsqRWJ8wnfFMT5M8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-clean-your-house-quickly-4118362-01-HERO-61844772294c447da5e8ab2b435fc670.jpg');
INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (2, 'https://www.teaforturmeric.com/instant-pot-chicken-curry/', 'Instant Pot Pakistani Chicken Curry With Potatoes', 'This Authentic Pakistani Instant Pot Chicken Curry (Aloo Murghi ka Salan or Aloo Chicken) recipe includes bone-in chicken and potatoes and requires less than 30 minutes of total prep time. It has simple ingredients, minimal chopping, and no complicated steps. Bonus: The potatoes and chicken cook at the same time!', 'https://www.teaforturmeric.com/wp-content/uploads/2019/11/Authentic-Instant-Pot-Chicken-Curry-Recipe-3-669x1024.jpg');
INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (4, 'https://www.cosmopolitan.com/food-cocktails/a6947/recipes-that-impress/', '15 Incredible Recipes That Will Impress Absolutely Anyone', 'There are a few dishes that, if you know how to make them at home, will definitely earn you praise. Theyre classic, theyre impressive, and they taste amazing. Perfect these 15 recipes and everyone will think you''re the best chef around.', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2018%2F09%2Fgordon-ramsay-hells-kitchen-02-2000.jpg&q=60');
INSERT INTO resources (owner_id, resource_url, title, description, img_url)
VALUES (1, 'https://www.muscleandfitness.com/workout-plan/workouts/workout-routines/complete-mf-beginners-training-guide-plan/', 'How to Do a Handstand', 'Whether youre just starting out―or starting again―this fast-track workout plan will help you drastically improve your physique and fitness levels.', 'https://www.mgactivewear.com/images/thumbs/0002734_1_900.png');
